// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbjrsrerfcoueonebktu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ianJzcmVyZmNvdWVvbmVia3R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjEyNjQsImV4cCI6MjA3MDQzNzI2NH0.7eU9ipZYFJfc7WEmrziTwqBjbue7WekgwZ-0m13iWXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});